<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>XpProbe</AssemblyName>
    <OutputPath>$(ManagedOutRoot)TestMods\</OutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoreLoader\CoreLoader.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
